chore(plugin): add plugin::use

diff --git a/core/git b/core/git
--- a/core/git
+++ b/core/git
@@ -165,6 +165,52 @@ git::url_ssh_to_http() {
   return 1
 }
 
+git::has_tag() {
+  local tag=$1
+  if [ -z "$tag" ]; then
+    log::error "[git::has_tag] tag is required"
+    return 1
+  fi
+
+  git ls-remote --exit-code origin refs/tags/$tag >>/dev/null 2>&1
+  if [ "$?" != "0" ]; then
+    echo "false"
+  else
+    echo "true"
+  fi
+}
+
+git::switch_tag() {
+  local tag=$1
+  if [ -z "$tag" ]; then
+    log::error "[git::switch_tag] tag is required"
+    return 1
+  fi
+
+  git fetch origin tag $tag >>/dev/null
+  if [ "$?" != "0" ]; then
+    log::error "[git::switch_tag] failed to fetch tag: $tag"
+    return 1
+  fi
+
+  git checkout $tag >>/dev/null
+}
+
+git::use_version() {
+  local version=$1
+  if [ -z "$version" ]; then
+    log::error "[git::use_version] version is required"
+    return 1
+  fi
+
+  # if [ "$(git::has_tag $version)" != "true" ]; then
+  #   log::error "[git::use_version] version($version) not found"
+  #   return 1
+  # fi
+
+  git::switch_tag $version
+}
+
 export -f git::commit_message
 export -f git::commit_message_full
 export -f git::commit_hash
@@ -193,3 +239,7 @@ export -f git::pull_request_url
 export -f git::merge_request_url
 
 export -f git::url_ssh_to_http
+
+export -f git::has_tag
+export -f git::switch_tag
+export -f git::use_version
diff --git a/core/plugin b/core/plugin
--- a/core/plugin
+++ b/core/plugin
@@ -559,6 +559,8 @@ plugin::run() {
     zmicro plugin register $plugin_name
   elif [ "$plugin_command_real" = "release" ]; then
     zmicro plugin release $plugin_name
+  elif [ "$plugin_command_real" = "use" ]; then
+    zmicro plugin use $plugin_name $plugin_command_args_real
   elif [ "$plugin_command_real" = "go" ]; then
     zmicro go plugin $plugin_name
   elif [ "$plugin_command_real" = "code" ]; then
@@ -811,6 +813,55 @@ plugin::get_remote_version() {
   echo $version
 }
 
+plugin::use() {
+  local name=$1
+  local version=$2
+
+  if [ -z "$name" ]; then
+    log::error "[$(timestamp)][plugin::use] plugin name is required"
+    exit 1
+  fi
+
+  if [ -z "$version" ]; then
+    log::error "[$(timestamp)][plugin::use] plugin version is required"
+    exit 1
+  fi
+
+  local plugin_path=$(plugin::get_path $name)
+  if [ ! -d "$plugin_path" ]; then
+    log::error "[$(timestamp)][plugin::use] plugin $name not found"
+    exit 1
+  fi
+
+  local version_origin=$(plugin::get_version $name)
+  if [ "$version_origin" = "$version" ]; then
+    log::info "[$(timestamp)][plugin::use] plugin $name version already is $version"
+    return 0
+  fi
+
+  # @TODO special version
+  if [ "$version" = "latest" ]; then
+    git checkout master >>/dev/null 2>&1
+    git pull origin master >>/dev/null 2>&1
+    log::success "[$(timestamp)][plugin::use] plugin $name version use $version success"
+    return
+  fi
+
+  if [ "$(git::has_tag $version)" != "true" ]; then
+    log::error "[$(timestamp)][plugin::use] plugin $name version $version not found"
+    exit 1
+  fi
+
+  cd $plugin_path
+  git::use_version $version
+  if [ "$?" != "0" ]; then
+    log::error "[$(timestamp)][plugin::use] plugin $name use version $version error"
+    exit 1
+  fi
+
+  log::success "[$(timestamp)][plugin::use] plugin $name version use $version success"
+}
+
 export -f plugin::register_all
 export -f plugin::register
 export -f plugin::unregister
@@ -867,3 +918,5 @@ export -f plugin::get_remote_url
 export -f plugin::get_remote_version
 
 export -f plugin::get_remote_mod_url
+
+export -f plugin::use
