fix(install): install::dmg unmount old dmg

diff --git a/core/install b/core/install
--- a/core/install
+++ b/core/install
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 # install::dmg installs mac dmg format package.
-# install::dmg@usage <dmg_path> <package_name> <app_name>
+# install::dmg@usage <dmg_path> <package_name> <app_name> [mount_path]
 # install::dmg@example:
 #    install::dmg $PWD/tmp/MiaoYan.dmg 妙言 MiaoYan.app
 install::dmg() {
@@ -27,6 +27,14 @@ install::dmg() {
   if [ -z "$app_name" ]; then
     log::error "[install::dmg] app name is required"
     return 1
+  fi
+
+  if [ -d "$mount_path" ]; then
+    hdiutil unmount "$mount_path" >>/dev/null
+    if [ "$?" != "0" ]; then
+      log::error "[install::dmg] failed to unmount old dmg."
+      return 1
+    fi
   fi
 
   # hdiutil attach $dmg_path
