feat(install): add install::tgz

diff --git a/core/install b/core/install
--- a/core/install
+++ b/core/install
@@ -181,6 +181,76 @@ install::zip() {
   log::success "[install::zip] succeed to install ${package_name}."
 }
 
+# install::tgz installs the tar.gz format package.
+# install::tgz@usage <tgz_path> <package_name> [base_path]
+# install::tgz@example:
+#    install::tgz $PWD/tmp/Spacedrive.tar.gz iTerm2 "iTerm.app"
+install::tgz() {
+  local tgz_path=$1
+  local package_name=$2
+  local app_name=$3
+  local base_path=${4:-"."}
+
+  if [ -z "$tgz_path" ]; then
+    log::error "[install::tgz] zip path is required"
+    return 1
+  fi
+
+  if [ -z "$package_name" ]; then
+    log::error "[install::tgz] package name is required"
+    return 1
+  fi
+
+  if [ -z "$app_name" ]; then
+    log::error "[install::tgz] app name is required"
+    return 1
+  fi
+
+  local system_app_path="/Applications/$app_name"
+  # if [ -d "$system_app_path" ]; then
+  #   log::error "[install::tgz] system application ${app_name} already exists"
+  #   return 1
+  # fi
+
+  local tmp_dir=$(os::tmp_dir)
+  local tmp_error_file=$(os::tmp_file)
+
+  log::info "[install::tgz] creating tmp dir ${tmp_dir} ..."
+  mkdir -p $tmp_dir
+
+  log::info "[install::tgz] go to tmp dir ..."
+  cd $tmp_dir
+
+  log::info "[install::tgz] extract zip $tgz_path ..."
+  os::tar -zxvf "$tgz_path" >>/dev/null 2>$tmp_error_file
+  if [ "$?" != "0" ]; then
+    log::error "[install::tgz] failed to extract file type(zip): $tgz_path."
+    log::error "[install::tgz] error detail: $(cat $tmp_error_file)"
+    return 1
+  fi
+
+  log::info "[install::tgz] show files ..."
+  ls -al
+
+  # os::install $source_bin_file $target_bin_dir $target_bin_name >>/dev/null 2>$tmp_error_file
+  cp -rf "${base_path%/}/${app_name}" /Applications
+  if [ "$?" != "0" ]; then
+    log::error "[install::tgz] failed to install $target_bin_name."
+    log::error "[install::tgz] error detail: $(cat $tmp_error_file)"
+    return 1
+  fi
+
+  log::info "[install::tgz] clear tmp dir ..."
+  rm -rf $tmp_dir >>/dev/null 2>$tmp_error_file
+  if [ "$?" != "0" ]; then
+    log::error "[install::tgz] failed to remove tmp dir: $(cat $tmp_error_file)"
+    return 1
+  fi
+
+  log::success "[install::tgz] succeed to install ${package_name}."
+}
+
 export -f install::dmg
 export -f install::pkg
 export -f install::zip
+export -f install::tgz
