fix(os): os::extract tar_xz for package shellcheck in docker

diff --git a/core/os b/core/os
--- a/core/os
+++ b/core/os
@@ -2046,8 +2046,15 @@ os::extract() {
   local tmp_error_file=$(os::tmp_file)
 
   if [ "$(os::is_file_type_tar_gz $filepath)" = "true" ]; then
-    set +e
     os::tar -zxvf $filepath >> /dev/null 2>$tmp_error_file
+    if [ "$?" != "0" ]; then
+      log::error "[os::extract] failed to extract file type(tar.gz): $filepath."
+      log::error "[os::extract] error detail: $(cat $tmp_error_file)"
+      return 1
+    fi
+  elif [ "$(os::is_file_type_tar_xz $filepath)" = "true" ]; then    
+    set +e
+    os::tar -Jxvf $filepath >> /dev/null 2>$tmp_error_file
     if [ "$?" != "0" ]; then
       # tar (child): xz: Cannot exec: No such file or directory
       if cat $tmp_error_file | grep "xz: Cannot exec"; then
@@ -2068,19 +2075,12 @@ os::extract() {
       fi
 
       # try again
-      os::tar -zxvf $filepath >> /dev/null 2>$tmp_error_file
+      os::tar -Jxvf $filepath >> /dev/null 2>$tmp_error_file
       if [ "$?" != "0" ]; then
-        log::error "[os::extract] failed to extract file type(tar.gz): $filepath."
+        log::error "[os::extract] failed to extract file type(tar.xz): $filepath."
         log::error "[os::extract] error detail: $(cat $tmp_error_file)"
         return 1
       fi
-    fi
-  elif [ "$(os::is_file_type_tar_xz $filepath)" = "true" ]; then
-    os::tar -Jxvf $filepath >> /dev/null 2>$tmp_error_file
-    if [ "$?" != "0" ]; then
-      log::error "[os::extract] failed to extract file type(tar.xz): $filepath."
-      log::error "[os::extract] error detail: $(cat $tmp_error_file)"
-      return 1
     fi
   elif [ "$(os::is_file_type_zip $filepath)" = "true" ]; then
     os::unzip -xo $filepath >> /dev/null 2>$tmp_error_file
