fix(os): os::extract tar_xz for package shellcheck in docker

diff --git a/core/os b/core/os
--- a/core/os
+++ b/core/os
@@ -2046,11 +2046,34 @@ os::extract() {
   local tmp_error_file=$(os::tmp_file)
 
   if [ "$(os::is_file_type_tar_gz $filepath)" = "true" ]; then
+    set +e
     os::tar -zxvf $filepath >> /dev/null 2>$tmp_error_file
     if [ "$?" != "0" ]; then
-      log::error "[os::extract] failed to extract file type(tar.gz): $filepath."
-      log::error "[os::extract] error detail: $(cat $tmp_error_file)"
-      return 1
+      # tar (child): xz: Cannot exec: No such file or directory
+      if cat $tmp_error_file | grep "xz: Cannot exec"; then
+        log::info "[os::extract] install xz utils..."
+        if [ "$(os::is_ubuntu)" = "true" ]; then
+          pm install -y xz-utils
+          if [ "$?" != "0" ]; then
+            log::error "[os::extract] failed to install xz-utils."
+            return 1
+          fi
+        else
+          pm install -y xz
+          if [ "$?" != "0" ]; then
+            log::error "[os::extract] failed to install xz."
+            return 1
+          fi
+        fi
+      fi
+
+      # try again
+      os::tar -zxvf $filepath >> /dev/null 2>$tmp_error_file
+      if [ "$?" != "0" ]; then
+        log::error "[os::extract] failed to extract file type(tar.gz): $filepath."
+        log::error "[os::extract] error detail: $(cat $tmp_error_file)"
+        return 1
+      fi
     fi
   elif [ "$(os::is_file_type_tar_xz $filepath)" = "true" ]; then
     os::tar -Jxvf $filepath >> /dev/null 2>$tmp_error_file
