chore(plugin): add plugin::has_update/plugin::get_remote_version method

diff --git a/core/plugin b/core/plugin
--- a/core/plugin
+++ b/core/plugin
@@ -741,6 +741,60 @@ plugin::update() {
   plugin::each fn
 }
 
+plugin::has_update() {
+  local name=$1
+  if [ -z "$name" ]; then
+    log::error "[$(timestamp)][plugin::check_update] plugin name is required"
+    exit 1
+  fi
+
+  local version=$(plugin::get_version $name)
+  local remote_version=$(plugin::get_remote_version $name)
+  if [ "$version" != "$remote_version" ]; then
+    echo "true"
+  else
+    echo "false"
+  fi
+}
+
+plugin::get_remote_url() {
+  local name=$1
+  if [ -z "$name" ]; then
+    log::error "[$(timestamp)][plugin::get_remote_url] plugin name is required"
+    exit 1
+  fi
+
+  echo "${ZMICRO_PLUGIN_REPO_PREFIX}${name}"
+}
+
+plugin::get_remote_mod_url() {
+  local name=$1
+  if [ -z "$name" ]; then
+    log::error "[$(timestamp)][plugin::get_remote_url] plugin name is required"
+    exit 1
+  fi
+
+  echo "https://raw.githubusercontent.com/zmicro-design/plugin-${name}/master/mod"
+}
+
+plugin::get_remote_version() {
+  local name=$1
+  if [ -z "$name" ]; then
+    log::error "[$(timestamp)][plugin::get_remote_version] plugin name is required"
+    exit 1
+  fi
+
+  local mod_url=$(plugin::get_remote_mod_url $name)
+  local mod_info=$(curl -s $mod_url 2>/dev/null)
+  if [ -z "$mod_info" ]; then
+    log::error "[$(timestamp)][plugin::get_remote_version] plugin $name mod info not found"
+    exit 1
+  fi
+
+  local version=$(echo -e "$mod_info" | grep "PLUGIN_VERSION=" | cut -d "=" -f 2)
+  echo $version
+}
+
 export -f plugin::register_all
 export -f plugin::register
 export -f plugin::unregister
@@ -791,3 +845,9 @@ export -f plugin::postinstall
 export -f plugin::version_echo
 
 export -f plugin::update
+
+export -f plugin::has_update
+export -f plugin::get_remote_url
+export -f plugin::get_remote_version
+
+export -f plugin::get_remote_mod_url
