chore(plugin): add env PLUGIN_CACHE

diff --git a/core/plugin b/core/plugin
--- a/core/plugin
+++ b/core/plugin
@@ -85,6 +85,7 @@ plugin::register() {
   plugin::get_app_configs_path $plugin_name >>/dev/null
   plugin::get_app_logs_path $plugin_name >>/dev/null
   plugin::get_app_data_path $plugin_name >>/dev/null
+  plugin::get_app_cache_path $plugin_name >>/dev/null
 }
 
 plugin::unregister() {
@@ -208,6 +209,22 @@ plugin::get_app_configs_path() {
   fi
 
   local path=$ZMICRO_PLUGINS_CONFIGS_PATH/$plugin_name
+  if [ ! -d $path ]; then
+    sudo mkdir -p $path
+    sudo chown $USER $path
+  fi
+
+  echo $path
+}
+
+plugin::get_app_cache_path() {
+  local plugin_name=$1
+  if [ -z $plugin_name ]; then
+    log::error "[plugin::get_app_cache_path] plugin name is required"
+    exit 1
+  fi
+
+  local path=$ZMICRO_PLUGINS_CACHE_PATH/$plugin_name
   if [ ! -d $path ]; then
     sudo mkdir -p $path
     sudo chown $USER $path
@@ -515,6 +532,7 @@ plugin::run() {
   export PLUGIN_DATA=$(plugin::get_app_data_path $plugin_name)
   export PLUGIN_LOGS=$(plugin::get_app_logs_path $plugin_name)
   export PLUGIN_CONFIGS=$(plugin::get_app_configs_path $plugin_name)
+  export PLUGIN_CACHE=$(plugin::get_app_cache_path $plugin_name)
   #
   export PLUGIN_CONFIG=$PLUGIN_CONFIGS/config
   #
@@ -711,6 +729,7 @@ plugin::shell() {
   export PLUGIN_DATA=$(plugin::get_app_data_path $plugin_name)
   export PLUGIN_LOGS=$(plugin::get_app_logs_path $plugin_name)
   export PLUGIN_CONFIGS=$(plugin::get_app_configs_path $plugin_name)
+  export PLUGIN_CACHE=$(plugin::get_app_cache_path $plugin_name)
   #
   export PLUGIN_CONFIG=$PLUGIN_CONFIGS/config
   #
@@ -1220,6 +1239,7 @@ export -f plugin::get_commands_path
 export -f plugin::get_app_data_path
 export -f plugin::get_app_logs_path
 export -f plugin::get_app_configs_path
+export -f plugin::get_app_cache_path
 
 export -f plugin::exist
 export -f plugin::bin_exist
